[2024-11-09T13:16:40.561+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-09T13:16:40.594+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_load.load_to_postgres manual__2024-11-09T12:16:15.825034+00:00 [queued]>
[2024-11-09T13:16:40.605+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_load.load_to_postgres manual__2024-11-09T12:16:15.825034+00:00 [queued]>
[2024-11-09T13:16:40.606+0100] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-09T13:16:40.623+0100] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-11-09 12:16:15.825034+00:00
[2024-11-09T13:16:40.633+0100] {logging_mixin.py:190} WARNING - /home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=38989) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-09T13:16:40.633+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgres_load', 'load_to_postgres', 'manual__2024-11-09T12:16:15.825034+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpylirk1ot']
[2024-11-09T13:16:40.634+0100] {standard_task_runner.py:72} INFO - Started process 39013 to run task
[2024-11-09T13:16:40.634+0100] {standard_task_runner.py:105} INFO - Job 24: Subtask load_to_postgres
[2024-11-09T13:16:40.756+0100] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_load.load_to_postgres manual__2024-11-09T12:16:15.825034+00:00 [running]> on host DESKTOP-SO44L49.
[2024-11-09T13:16:40.906+0100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_postgres_load' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-09T12:16:15.825034+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-09T12:16:15.825034+00:00'
[2024-11-09T13:16:40.907+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-09T13:16:40.908+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-09T13:16:40.908+0100] {logging_mixin.py:190} INFO - Current task name:load_to_postgres state:running start_date:2024-11-09 12:16:40.595325+00:00
[2024-11-09T13:16:40.909+0100] {logging_mixin.py:190} INFO - Dag name:etl_postgres_load and current dag run status:running
[2024-11-09T13:16:40.909+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-09T13:16:40.941+0100] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-09T13:16:40.973+0100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow/dags/test.py", line 48, in load_to_postgres
    with open(file_path, 'r') as csv_file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/hajar/airflow/data/fixed_transformed_train.csv'
[2024-11-09T13:16:41.019+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-09T13:16:41.020+0100] {logging_mixin.py:190} INFO - Task start:2024-11-09 12:16:40.595325+00:00 end:2024-11-09 12:16:41.018642+00:00 duration:0.423317
[2024-11-09T13:16:41.020+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_postgres> dag:<DAG: etl_postgres_load> dagrun:<DagRun etl_postgres_load @ 2024-11-09 12:16:15.825034+00:00: manual__2024-11-09T12:16:15.825034+00:00, state:running, queued_at: 2024-11-09 12:16:15.848537+00:00. externally triggered: True>
[2024-11-09T13:16:41.021+0100] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/home/hajar/airflow/data/fixed_transformed_train.csv'
[2024-11-09T13:16:41.021+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_postgres_load, task_id=load_to_postgres, run_id=manual__2024-11-09T12:16:15.825034+00:00, execution_date=20241109T121615, start_date=20241109T121640, end_date=20241109T121641
[2024-11-09T13:16:41.045+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-09T13:16:41.046+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task load_to_postgres ([Errno 2] No such file or directory: '/home/hajar/airflow/data/fixed_transformed_train.csv'; 39013)
Traceback (most recent call last):
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow/dags/test.py", line 48, in load_to_postgres
    with open(file_path, 'r') as csv_file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/hajar/airflow/data/fixed_transformed_train.csv'
[2024-11-09T13:16:41.092+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-09T13:16:41.192+0100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-09T13:16:41.201+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
